// react/src/App.tsx
import reactLogo from "./assets/react.svg"
import "./App.css"

import { BrowserRouter, Routes, Route } from "react-router-dom"

const NavBar = () => <nav>NavBar</nav>

const Home = () => (
    <div>
        <h1 className="title">Home Page</h1>
        <h2 className="subtitle">This is our home page</h2>
    </div>
)

function App() {
    return (
        <BrowserRouter>
            <img src={reactLogo} className="logo react" alt="React logo" />{" "}
            <header>
                <NavBar />
            </header>
            <div className="container">
                <Routes>
                    <Route path="/" element={<Home />} />
                    <Route path="/about" element={<div>About</div>} />
                    <Route path="/contact" element={<div>Contact</div>} />
                </Routes>
            </div>
        </BrowserRouter>
    )
}

export default App

// Client/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <header>
    <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="125" height="125" />

    <div class="wrapper">

      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </nav>
    </div>
  </header>

  <RouterView />
</template>

<style scoped>

</style>
